// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Prediction model parameters for Image Classification.
public struct ImageClassificationPredictionParams: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The Model only returns predictions with at least this confidence score.
  /// Default value is 0.0
  public var confidenceThreshold: Swift.Float = Swift.Float()

  /// The Model only returns up to that many top, by confidence score,
  /// predictions per instance. If this number is very high, the Model may return
  /// fewer predictions. Default value is 10.
  public var maxPredictions: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `ImageClassificationPredictionParams`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageClassificationPredictionParams().with { $0.confidenceThreshold = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.predict.params.ImageClassificationPredictionParams"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
