// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Prediction model parameters for Video Object Tracking.
public struct VideoObjectTrackingPredictionParams: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The Model only returns predictions with at least this confidence score.
  /// Default value is 0.0
  public var confidenceThreshold: Swift.Float = Swift.Float()

  /// The model only returns up to that many top, by confidence score,
  /// predictions per frame of the video. If this number is very high, the
  /// Model may return fewer predictions per frame. Default value is 50.
  public var maxPredictions: Swift.Int32 = Swift.Int32()

  /// Only bounding boxes with shortest edge at least that long as a relative
  /// value of video frame size are returned. Default value is 0.0.
  public var minBoundingBoxSize: Swift.Float = Swift.Float()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VideoObjectTrackingPredictionParams`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoObjectTrackingPredictionParams().with { $0.confidenceThreshold = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let confidenceThreshold = CodingKeys(stringValue: "confidenceThreshold")
    static let maxPredictions = CodingKeys(stringValue: "maxPredictions")
    static let minBoundingBoxSize = CodingKeys(stringValue: "minBoundingBoxSize")

    static let _knownKeys: Set<Swift.String> = [
      "confidenceThreshold",
      "maxPredictions",
      "minBoundingBoxSize",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .confidenceThreshold) {
      self.confidenceThreshold = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxPredictions) {
      self.maxPredictions = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .minBoundingBoxSize) {
      self.minBoundingBoxSize = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.confidenceThreshold, forKey: .confidenceThreshold)
    try container.encode(self.maxPredictions, forKey: .maxPredictions)
    try container.encode(self.minBoundingBoxSize, forKey: .minBoundingBoxSize)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.predict.params.VideoObjectTrackingPredictionParams"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
