// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Prediction model parameters for Video Classification.
public struct VideoClassificationPredictionParams: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The Model only returns predictions with at least this confidence score.
  /// Default value is 0.0
  public var confidenceThreshold: Swift.Float = Swift.Float()

  /// The Model only returns up to that many top, by confidence score,
  /// predictions per instance. If this number is very high, the Model may return
  /// fewer predictions. Default value is 10,000.
  public var maxPredictions: Swift.Int32 = Swift.Int32()

  /// Set to true to request segment-level classification. Vertex AI returns
  /// labels and their confidence scores for the entire time segment of the
  /// video that user specified in the input instance.
  /// Default value is true
  public var segmentClassification: Swift.Bool = Swift.Bool()

  /// Set to true to request shot-level classification. Vertex AI determines
  /// the boundaries for each camera shot in the entire time segment of the
  /// video that user specified in the input instance. Vertex AI then
  /// returns labels and their confidence scores for each detected shot, along
  /// with the start and end time of the shot.
  /// WARNING: Model evaluation is not done for this classification type,
  /// the quality of it depends on the training data, but there are no metrics
  /// provided to describe that quality.
  /// Default value is false
  public var shotClassification: Swift.Bool = Swift.Bool()

  /// Set to true to request classification for a video at one-second intervals.
  /// Vertex AI returns labels and their confidence scores for each second of
  /// the entire time segment of the video that user specified in the input
  /// WARNING: Model evaluation is not done for this classification type, the
  /// quality of it depends on the training data, but there are no metrics
  /// provided to describe that quality. Default value is false
  public var oneSecIntervalClassification: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `VideoClassificationPredictionParams`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoClassificationPredictionParams().with { $0.confidenceThreshold = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.aiplatform.v1.schema.predict.params.VideoClassificationPredictionParams"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
